baseURL = 'https://georgenixon.co.uk/'
languageCode = 'en-us'
theme = 'terminal'
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2

[languages]
  [languages.en]
    title = "George Nixon"
    [languages.en.params]
      subtitle = "Things I've figured out, so you don't have to. Or that an LLM figured out with me, and I'm stealing the credit."
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      menuMore = "Show more"
    [languages.en.params.logo]
      logoText = "$ cd /home/george"
      logoHomeLink = "/"
