baseURL = 'https://georgenixon.co.uk/'
locale = 'en-us'
title = 'George Nixon'
theme = 'PaperMod'

[params]
  description = "Things I've figured out, so you don't have to. Or that an LLM figured out with me, and I'm stealing the credit."

[params.assets]
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "/favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"
  safari_pinned_tab = "/safari-pinned-tab.svg"
